import type { Metadata } from 'next';
import Link from 'next/link';
import { Header } from '../proposal';
import { sources as s } from '../sources';
import '../style.css';

export const metadata: Metadata = { title: 'Heartracer — Research Appendix | Crowd Control Digital', robots: { index: false, follow: false } };
function External({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} target="_blank" rel="noreferrer">{children} ↗</a>; }
function Table({ heads, rows }: { heads: string[]; rows: React.ReactNode[][] }) { return <div className="hr-table-scroll"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>; }

export default function Research() { return <div className="hr"><Header research /><main>
  <section className="hr-research-hero"><div className="hr-wrap"><span className="hr-mono">RESEARCH APPENDIX / SNAPSHOT SEPTEMBER 29, 2026</span><h1>The evidence.<br /><span className="hr-display">The decisions.</span></h1><p>A source-led assessment of Heartracer’s release, social creative and listener response. Public post metrics were collected through Apify; the discovery conversation came from Granola. Recommendations are separated from observations throughout.</p><nav className="hr-research-nav" aria-label="Research sections">{[['brief','The brief'],['platforms','Platform audit'],['creative','Creative teardown'],['sentiment','Sentiment'],['audience','Audience tests'],['benchmarks','Benchmarks'],['execution','Execution'],['commercial','Commercial model'],['sources','Sources']].map(([id,name])=><a href={'#'+id} key={id}>{name}</a>)}</nav></div></section>
  <div className="hr-research-content"><div className="hr-wrap">
    <section id="brief"><span className="hr-mono">01 / CONTEXT</span><h2>A record with a runway.</h2><p><em>Nighttime Fever</em> is a nine-track third studio album, publicly listed for October 23, 2026. The September 29 conversation describes approximately two and a half years of work, five finished videos, two released singles and a third arriving October 2. The band wants the record to keep finding listeners after release, with longer-term ambitions around sync and a musically aligned support slot.</p><Table heads={['Finding','Evidence status','Implication']} rows={[
      ['Nine tracks; October 23 album date','Official website and Bandcamp','Anchor the calendar to the verified album release.'],
      ['Five videos; existing Excel email list','Reported in the discovery conversation','Inventory the actual footage and activate the existing list.'],
      ['Self-released through DistroKid','Band-reported','Confirm release links, rights and delivery dates in onboarding.'],
      ['Irish ads prompted messages','Band-reported; conversion unverified','Run a controlled Ireland test rather than treating messages as purchase evidence.'],
      ['Sync and support-slot ambitions','Band-reported','Longer-term career context shared by the band.'],
      ['Gallery5 show on October 3','Current Instagram and Facebook event posts','Use the local show for live footage and consent-based fan capture.'],
      ['Historical APM publishing relationship','Richmond Magazine, August 2023','Confirm current rights and usage permissions for campaign assets.'],
    ]}/><div className="hr-research-note"><p>The proposal follows the requested written offer: $4,000/month, 15% of managed media spend and $100/hour for approved creative. The call discussed a 10% media fee. The written 15% needs to be stated clearly when presenting the offer. No media budget or final start date was agreed in the call.</p></div><p>The band-reported Spotify listener estimate is not a verified current baseline. No private streaming, ad-account, ticket-sales or email-performance data were available. A public follower count is an account-size observation, not a count of active fans.</p></section>

    <section id="platforms"><span className="hr-mono">02 / DISTRIBUTION & PROFILE AUDIT</span><h2>Reach and response tell different stories.</h2><Table heads={['Platform','Coverage / collection','Public baseline','Decision']} rows={[
      [<External href={s.instagram}>Instagram</External>,'Apify: profile + 60 posts; May 14–Sep 29. Dataset sorted by timestamp after collection.','19,723 followers; 359 total account posts. Sample: 43 videos, 15 images, 2 carousels. Median 10 likes and 0 comments.','Prioritize listener response, clear positioning and returning fans before judging success by follower totals.'],
      [<External href="https://www.tiktok.com/@playheartracermusic">TikTok</External>,'Apify: 60 videos; Apr 16, 2024–Sep 29, 2026. Comments collected separately.','91 followers; 89 account videos; sample median 149 plays. Latest-biased sample spans multiple years.','Treat it as a creative learning channel. Keep band content coherent; verify unusual metric clusters in native analytics.'],
      [<External href={s.facebook}>Facebook</External>,'Apify: 40 posts; Aug 10–Sep 29, 2026.','Median 8.5 recorded likes/reactions and 0 shares. 26 video posts; 14 other posts.','Make local events and paid distribution useful; provide clickable destinations rather than relying on a generic bio instruction.'],
      [<External href={s.youtube}>YouTube</External>,'Public channel extraction: 30 long-form entries + 23 Shorts; five long-form comment threads and three Shorts checked.','585 subscribers; 23-Short sample median 75 views. One Dublin Short: 208,707 views.','Test the discovery-to-full-song path. Ask for actual subscriber and returning-viewer attribution before scaling an outlier.'],
      [<External href={s.twitter}>X</External>,'Linked public profile; no post-level dataset collected.','No current metric claim.','Keep profile and release link accurate; defer an expanded publishing commitment until account activity is verified.'],
      [<External href={s.official}>Website / Linktree</External>,'Official-site review, public links and commerce-related comment evidence.','Existing mailing-list entry point; release, show and merchandise destinations compete for attention.','Build one current-release listening destination and a distinct show/ticket path. Audit international checkout.'],
    ]}/><h3>Instagram: the issue is bigger than posting frequency.</h3><p>The bio already names the album and October 23 date, identifies Virginia and directs listeners to the singles. Keep those useful elements. The current feed mixes release reminders, scenic Virginia images, other-artist recommendations, show promotion, merchandise and the “Fever Symptom” series. This offers personality, but the connective story between the musicians and their own record is uneven.</p><p>Across the 43 sampled videos, the median reported play count is 288 and the median reported video view count is 82. These are separate platform fields, not interchangeable measures of reach. The median of 10 likes divided by the snapshot’s 19,723 followers is about 0.05%; that calculation is a directional visible-interaction comparison, not an impression-based engagement rate. It does not establish fake followers, algorithm suppression or the effect of advertising.</p><Table heads={['Instagram example','Observed counts','Useful signal / next test']} rows={[
      [<External href="https://www.instagram.com/p/DbLSlDhOI2i/">Ireland pub anecdote / Jul 24</External>,'140 likes; 10,915 plays','A specific first-person story outperformed the sample median. Test story → song payoff, with attribution verified.'],
      [<External href="https://www.instagram.com/p/DbVeuN7ODka/">Dublin love-letter teaser / Jul 28</External>,'127 likes; 20,028 plays','Place and emotional specificity are a useful creative hypothesis. Paid support is unknown.'],
      [<External href="https://www.instagram.com/p/Db1Av3XFjyw/">Sunroom behind the scenes / Aug 9</External>,'47 likes; 7 comments','Production access can make the campaign feel lived-in; several comments were promotional solicitations.'],
      [<External href="https://www.instagram.com/p/DdEmIPOJofd/">Moonlight video reminder / Sep 9</External>,'42 likes; 632 plays','A useful launch asset; compare a performance-first edit with the calendar-first announcement.'],
      [<External href="https://www.instagram.com/p/DdZHKAxuCPU/">Gallery5 show / Sep 17</External>,'41 likes; 3 comments','A listener expressed attendance intent. Capture live footage and follow actual ticket data.'],
      [<External href="https://www.instagram.com/p/Dc01GV6vRSD/">Merch post / Sep 3</External>,'8 likes; 4 reported comments','The thread contains an international-shipping question and a country-selector problem report. Test checkout before promotion.'],
    ]}/><h3>TikTok: choose the identity the account should build.</h3><p>The account includes music, songwriting, vocal demonstrations and unrelated consumer or shopping-cart commentary. The highest-play item in the sample is a 2024 packaged-cookie complaint: 2,427 plays and 13 reported comments. Those reactions are about packaging and price, and must not be interpreted as sentiment about Heartracer’s music.</p><p>Three April 2026 music posts report unusually high likes relative to plays: the album-mastering update has 633 likes / 1,295 plays, the vocal demonstration 450 / 956, and the Dublin sample 365 / 1,414. These fields need native-account verification before being used as performance benchmarks. They do not establish purchased engagement. Preserve the songwriting and vocal ideas, then test them prospectively.</p><h3>YouTube: a large outlier needs a useful destination.</h3><Table heads={['Asset / upload date','Views','Likes','Comments','Interpretation']} rows={[
      [<External href={s.short}>Dublin release teaser / Aug 5, 2026</External>,'208,707','125','0','0.060% likes/views. Source of distribution and subscriber attribution unknown.'],
      [<External href={s.dublin}>Streets of Dublin / Aug 8, 2026</External>,'1,474','69','27','4.68% likes/views; comments give driving, replay and tour signals.'],
      [<External href={s.moonlight}>Dancin’ In The Moonlight / Sep 11, 2026</External>,'416','17','7','4.09% likes/views; one discovery reply names Michael Oakley.'],
      [<External href={s.dateNight}>Date Night / Feb 10, 2023</External>,'45,037','97','19','One listener describes discovering it in an ad and subsequently saving/following.'],
      [<External href={s.room}>We Should Never Leave This Room / Apr 21, 2023</External>,'40,092','94','16','Music praise and visibility concern; lifetime counts are not a current-campaign comparison.'],
      [<External href={s.ghost}>Living Like A Ghost / Jun 2, 2023</External>,'35,144','69','16','Collaboration demonstrates catalog breadth; collaborator comments excluded from fan sentiment.'],
    ]}/><p>The new single’s audio release on September 4 and official video upload on September 11 create a seven-day release gap. That can be deliberate, but the campaign should explain the two moments. A Short references October 3 while current single announcements say October 2; October 3 is also the local show date. Reconcile those messages before scheduling paid launch assets.</p><p>All counts are a September 29 snapshot. Posts have different ages, formats and distribution histories. Likes are not unique engaged users; plays can include repeat viewing. No paid/organic split, impressions, completion rates or audience demographics were available.</p><a className="hr-download" href="/research/heartracer/social-post-metrics.csv" download>Download the 160-post Apify metrics table ↓</a></section>

    <section id="creative"><span className="hr-mono">03 / CREATIVE TEARDOWN</span><h2>A world worth making clearer.</h2><div className="hr-research-art"><figure><img src="/images/heartracer/dublin.jpg" alt="Official Streets of Dublin thumbnail" /><figcaption>Dublin: a recognizable face and a specific place.</figcaption></figure><figure><img src="/images/heartracer/moonlight.jpg" alt="Official Dancin’ In The Moonlight thumbnail" /><figcaption>Moonlight: monochrome intimacy and a visible performer.</figcaption></figure></div><p>The brand’s strongest ingredients are cinematic place, melodic sincerity, live musicianship and contemporary nostalgia. The album artwork’s forest, yellow title and red waveform provide a repeatable visual reference. Dublin’s public storyboard frames show waterside performance and pub scenes; Moonlight’s opening storyboard frames show a monochrome ornate interior and a yellow vintage-style title. These observations come from thumbnails and sampled storyboard frames—not a full audiovisual or retention-curve review.</p><Table heads={['Element','Keep','Improve / test']} rows={[
      ['Positioning','Richmond origin; synth-pop and alternative-rock identity; emotionally specific songs.','Connect nostalgia to a present-day feeling: a night drive, a remembered place, a song you return to. Avoid generic genre hashtags as the entire proposition.'],
      ['First frame / opening','Faces, guitar detail, atmosphere and credible performance footage.','Test an immediate musical impact or a personal sentence before release-date text. Evaluate 3-second and deeper retention in native analytics.'],
      ['Fever Symptom series','An existing serial format and an album-world idea.','Make each episode work for a first-time listener: band name, actual song payoff and one clear action. Compare with a simpler performance edit.'],
      ['Other-artist recommendation series','Chris’s taste and specificity make him a person people can know.','Tie a recommendation to Heartracer’s own writing or performance. Keep commentary generous; criticism of other artists can distract from the band’s invitation.'],
      ['Caption and call to action','Humor, informal warmth and active replies.','Replace broad appeals to help the algorithm with a concrete listening benefit. One primary action per asset. Proofread song names, dates, hashtags and URLs.'],
      ['Format and design','High-quality supplied videos; distinctive album art.','Create intentional 9:16 crops, subtitle spoken passages, keep overlays inside platform safe areas, and preserve a face or musical gesture as the focal point.'],
      ['Destinations','Dublin’s song-specific Feature.fm link and an existing mailing-list path.','Moonlight’s description begins with an artist-level Spotify link; switch to the promoted song or intentional release hub. Verify the linktree.com vs. linktr.ee reference.'],
      ['Live proof','Official archive performance photographs and the upcoming Gallery5 show.','Capture crowd-inclusive live clips, a strong chorus and a band introduction. Label archive material accurately rather than presenting it as a current tour.'],
      ['Conversion','An existing list and merchandise offer.','Test mobile listening, email confirmation and international shipping end to end. A fan’s checkout complaint is an actionable signal, not a verified site diagnosis.'],
    ]}/><h3>Three production briefs, one musical identity.</h3><div className="hr-research-columns"><div><h3>The night drive</h3><p>Use Dublin’s strongest musical payoff and the observed driving-playlist behavior. Compare a vocal-first edit with an instrumental reveal. Use an available-song listening destination. Keep geography and creative separate in reporting.</p><h3>Inside the room</h3><p>Film Chris or Chip explaining one detail from the record, then immediately demonstrate it. Test candid story versus stripped performance. The band records supplied prompts; editing hours are estimated separately.</p></div><div><h3>Fever after dark</h3><p>Unify the artwork, performance and October single around an after-dark emotional world. Do not rely on a viewer having seen earlier symptoms. Before release, direct listeners to an available single; after October 23, switch to the album.</p><h3>A practical first batch</h3><p>Two opening variants for each of the three directions: six initial ad variants. Agree rights, dimensions, captions, destinations and revision allowance before production. Review delivery and response before making the next batch.</p></div></div></section>

    <section id="sentiment"><span className="hr-mono">04 / MANUALLY CODED PUBLIC COMMENTS</span><h2>Warmth, with limits.</h2><div className="hr-research-stats"><div><strong>176</strong><span>Retrieved comment rows across four platforms</span></div><div><strong>78</strong><span>Retained comments after documented exclusions</span></div><div><strong>67</strong><span>Positive comments in the retained sample</span></div><div><strong>11</strong><span>Neutral, practical or conversational comments</span></div></div><Table heads={['Platform','Retrieved','Excluded','Retained','Positive / neutral / negative']} rows={[
      ['YouTube','85','48','37','35 / 2 / 0'],['Instagram','37','20','17','12 / 5 / 0'],['TikTok','26','15','11','11 / 0 / 0'],['Facebook','28','15','13','9 / 4 / 0'],['Total','176','98','78','67 / 11 / 0'],
    ]}/><p>Facebook exclusions: nine band/team comments, two conversational replies and four unrelated lifestyle comments. Four empty/private scraper responses were excluded before counting comments. These are comment-level classifications, not a survey, a unique-person count or a representative measure of the entire audience. YouTube’s retained sample contains 31 distinct account handles. Accounts are not deduplicated across platforms. The pooled positive share is 85.9%, but it should not be used as a market-wide approval rating or a claim that no criticism exists.</p><p>YouTube exclusions: 40 band/team comments, three known collaborator comments, two conversational replies and three uninterpretable comments. Instagram exclusions: seven band comments, six generic promotional solicitations, two known scheduled-performer comments, three conversational replies, one comment about another artist and one empty comment. One additional scraper error row was excluded before counting comments. TikTok exclusions: eleven comments on an unrelated cookie-packaging complaint, one featured collaborator and three ambiguous emoji comments.</p><p>Every retained row was reviewed in context. Explicit praise, clear positive reaction emoji and stated attendance anticipation were coded positive. Questions, logistics and non-evaluative conversation were neutral. A negative music or band-attitude statement would be negative; none was observed in the retained sample. Shopping friction is tracked separately rather than mislabeled as criticism of the music.</p><Table heads={['Observed theme','Evidence','Campaign implication']} rows={[
      ['Music fits a listener’s day','Dublin listener: “This is going straight to my driving playlist!”','Test the night-drive invitation. Confirm saves and returning listeners in platform analytics.'],
      ['An adjacent artist can introduce the band','Moonlight reply describes discovering Heartracer through Michael Oakley and retro-music search. Reply excluded from sentiment denominator.','Test adjacent-artist discovery as a hypothesis; one reply does not establish a whole audience segment.'],
      ['Advertising has created a fan journey before','Date Night listener describes an ad interruption, watching instead of skipping, adding the band to a Spotify playlist and subscribing.','Preserve a strong musical opening and a specific song destination. Self-report is a useful clue, not measured conversion attribution.'],
      ['Live intent is present','One Dublin comment requests an England tour; one Gallery5 comment expresses plans to attend.','Collect city preferences and follow ticket data; do not infer a profitable international tour.'],
      ['Purchase interest meets practical friction','Instagram merchandise thread asks about international shipping; follow-up reports USA-only country selection.','Check fulfillment and checkout immediately. Respond with a verified option once resolved.'],
      ['A personal brand can produce unrelated engagement','Eleven TikTok comments discuss packaging, prices and politics on a cookie video.','Keep off-topic engagement outside music sentiment and acquisition reporting.'],
    ]}/><div className="hr-research-note"><p>Selection favors available public threads and Instagram posts with comments and selected higher-reaction Facebook posts. Counts are small, historical content is mixed with current releases, and moderation or missing comments can change the sample. Positive emoji offer weaker evidence than a specific action. Paid support, commenter authenticity and the identities of every acquaintance cannot be verified from public data.</p></div><a className="hr-download" href="/research/heartracer/comment-audit.csv" download>Download the coded audit and exclusion reasons ↓</a><p className="hr-small">The public audit includes comment identifiers, source links and labels. It does not reproduce the complete comment texts or the private Granola transcript. Facebook comments were collected on ten selected posts; four inputs returned empty/private responses. The sample includes a Widnes listener’s music praise, a Neo80s group-sharing report and a guitar-effects question answered by Chip.</p></section>

    <section id="audience"><span className="hr-mono">05 / TESTABLE AUDIENCE STRATEGY</span><h2>Find the audience through behavior.</h2><p>The available evidence supports hypotheses about listening use cases and discovery routes. It does not support invented age bands, gender proportions, income levels or city rankings. Prioritize those questions in onboarding rather than filling the gaps with stereotypes about synth-pop listeners.</p><Table heads={['Hypothesis','Test design','Evidence to decide']} rows={[
      ['Cinematic listeners respond to an immediate song moment','Compare vocal and instrumental openings within one agreed market, objective and destination. Keep placement and spend comparable.','Qualified listening-page visits, completion depth and native saves/follows where attributable.'],
      ['Artist context creates stronger returning interest','Compare a candid writing detail with a finished-performance edit. Keep song and action constant.','Meaningful replies, profile-to-follow behavior, email sign-ups and repeat engagement.'],
      ['Ireland is a useful discovery market','Run separate Ireland and US cells using the same creative and song destination; report currency and placement consistently.','Cost and quality of confirmed outcomes, not just messages or cheap views. A market win needs repeated evidence.'],
      ['Adjacent synth-pop exploration introduces relevant listeners','Test an available adjacent-interest audience against a broader music audience; avoid implying interest targeting guarantees fandom.','Compare completed listening intent and retained engagement, not click-through alone.'],
      ['The local show can strengthen owned connection','Offer a clear, consent-based sign-up invitation before/at the October 3 event; collect city and source where practical.','Verified sign-ups, later email clicks and ticket-linked data where permission and tooling support it.'],
    ]}/><p>Start with Meta for discovery and retargeting where account eligibility allows it. Add YouTube when budget and the first creative tests support a meaningful second channel. Reserve roughly 20% of the agreed test budget for the Ireland comparison initially; that allocation is a planning assumption, not a fixed buy or a result forecast. At low budgets, sequence tests rather than dividing spend across every platform and audience at once.</p><h3>Measurement hierarchy</h3><p>Use views and reach to diagnose distribution, listening-page visits to diagnose intent, native saves/follows and confirmed email sign-ups to diagnose deeper response, and repeated behavior to assess retention. Email sign-ups are an owned audience outcome; platform streams and ticket purchases require their own evidence. There is no assumed click-to-stream multiplier.</p><p>By day seven: confirm baselines and tracking definitions. By day thirty: evaluate six initial variants and a welcome path. By month three: identify useful repeatable creative, usable geography evidence and the next campaign decision. Set numeric acquisition targets after the first baseline, with a written definition for every metric.</p></section>

    <section id="benchmarks"><span className="hr-mono">06 / ADJACENT CREATIVE REFERENCES</span><h2>Borrow the mechanics. Keep the identity.</h2><Table heads={['Reference','Publicly observed mechanic','Adaptation for Heartracer']} rows={[
      [<External href={s.midnight}>The Midnight</External>,'An album world connected to touring, merchandise and direct fan updates; official site includes a Laylo sign-up mechanism.','Make artwork, story, listening and fan capture feel like one current chapter. No assumption of comparable scale or budget.'],
      [<External href={s.strike}>The Strike</External>,'Official site routes listeners through music, live shows, video and other band material; a clear performance identity.','Show what the trio delivers live and make the show action easy to find. Support-slot ambition needs live proof.'],
      [<External href={s.oakley}>Michael Oakley</External>,'A clear current album presentation and accessible catalog. One Heartracer listener explicitly names this discovery route.','Use focused release routing and adjacent discovery as a controlled test. That one listener is an anecdote, not a measured affinity index.'],
    ]}/><p>These are selected creative and funnel references, not a ranked competitor market study. No current follower totals, media budgets or campaign returns are inferred. The band’s own stated aspirational reference points—The Killers, Sam Fender, The War on Drugs, M83 and Empire of the Sun—guide creative language and opportunity fit; they do not establish reachable booking outcomes.</p></section>

    <section id="execution"><span className="hr-mono">07 / PRIORITIES & WORKING RHYTHM</span><h2>Make the first week count.</h2><Table heads={['Priority','Action','Owner / dependency']} rows={[
      ['Before kickoff','Confirm written fee, October 1–December 31 initial term, first-month invoice and media/creative caps.','CCD + one band decision maker.'],
      ['Day 1–2','Verify release dates, Gallery5 show details, account invitations, existing email permissions and current rights/publishing relationships.','Band supplies source records; CCD builds launch checklist.'],
      ['Day 1–3','Audit listening links, mobile capture, checkout countries and confirmation emails.','CCD coordinates; site/fulfillment owner implements required changes.'],
      ['Day 2–5','Approve six starting creative variants, current song destinations and initial market allocation.','CCD briefs; band supplies footage or approves production estimate.'],
      ['October 3 show','Capture a chorus, crowd context and a short band story; invite usable opt-ins.','Band/approved shooter; permissions and venue access required.'],
      ['Weekly','Review one concise performance snapshot, one creative decision and next week’s approvals.','Weekly working call; named lead and band approver.'],
      ['Monthly','Report spend, fee reconciliation, audience response and next tests.','CCD; platform data quality stated explicitly.'],
      ['By December','Deliver a three-month review and next-quarter content and media plan.','Creative performance, spend efficiency and audience-quality findings inform the recommendations.'],
    ]}/><h3>The operating agreement</h3><p>The proposal includes ongoing organic content planning and scheduling across two agreed channels with no fixed monthly post cap, two email campaigns monthly, one welcome message and initial standard list migration. Posting cadence follows the release plan, available approved assets and audience response. The retainer includes direction, captions and coordination. Editing, design and production are approved separately at $100/hour. Specify turnaround, asset delivery, revision allowances, software costs and account permissions before kickoff. Budget ownership stays with the band.</p></section>

    <section id="commercial"><span className="hr-mono">08 / COMMERCIAL MODEL</span><h2>The full cost, visible.</h2><p>Monthly total = $4,000 retainer + platform media spend + 15% of actual net managed media spend + $100 × approved creative hours. The platform buy is paid directly to platforms. The fee excludes platform taxes, credits and refunds. Production uses approved estimates and actual tracked time. Software, applicable taxes and approved outside expenses are additional.</p><Table heads={['Illustrative level','Media','Management','Creative','Agency + creative','All-in month','Same mix / 3 months']} rows={[
      ['Initial test','$2,000','$300','10 hrs / $1,000','$5,300','$7,300','$21,900'],
      ['Working example','$3,000','$450','20 hrs / $2,000','$6,450','$9,450','$28,350'],
      ['Broader test','$5,000','$750','30 hrs / $3,000','$7,750','$12,750','$38,250'],
      ['Retainer only','$0','$0','0 hrs / $0','$4,000','$4,000','$12,000'],
    ]}/><p>No level is agreed. The retainer-only row is a fee illustration and does not fund new creative production or paid distribution. At modest media budgets, the service fee is a significant part of the overall investment: at the $2,000 / 10-hour example, agency and creative account for about 73% of the total. That makes a realistic asset plan and a clear three-month review especially important.</p><p>The initial proposed term is three months, paid monthly in advance, without a setup fee or an annual commitment. The first $4,000 payment covers month one’s retainer; it should not be described as an additional deposit on top of that month. Any renewal, cancellation provisions and creative rights belong in the agreement. The page currently routes to invoice request until an authenticated Stripe payment link can be created.</p><Link className="hr-download" href="/heartracer#investment">Return to the interactive budget model ↗</Link></section>

    <section id="sources"><span className="hr-mono">09 / SOURCE LEDGER</span><h2>Trace every material claim.</h2><ol className="hr-source-list">{[
      [s.meeting,'Granola discovery conversation','Crowd Control <> Chris Cosby, September 29, 2026. Private source; access depends on Granola permissions. Not reproduced publicly.'],
      [s.official,'Heartracer official website','Band identity, current album date, links and archive media.'],[s.album,'Nighttime Fever on Bandcamp','Nine tracks, album artwork and October 23 release date.'],[s.linktree,'Official Linktree','Profile and campaign destinations; handle discovery.'],[s.instagram,'Instagram / @playheartracer','Profile and 60 posts via Apify Instagram Scraper; comments via Instagram Comment Scraper.'],['https://www.tiktok.com/@playheartracermusic','TikTok / @playheartracermusic','60 posts and comment dataset via Clockworks TikTok Scraper on Apify.'],[s.facebook,'Facebook / playheartracer','40 public posts via Apify Facebook Posts Scraper.'],[s.youtube,'YouTube / Heartracer','Public channel inventories and exact video/comment metadata.'],[s.dublin,'Streets of Dublin video','Video metrics, description and public listener comments.'],[s.moonlight,'Dancin’ In The Moonlight video','Video metrics and adjacent-artist discovery reply.'],[s.dateNight,'Date Night lyric video','Historical metrics and self-reported advertising discovery.'],[s.short,'Dublin teaser Short','208,707-view outlier; paid/organic attribution unavailable.'],[s.richmond,'Richmond Magazine: A Kinetic Beat','August 2023 historical coverage; APM relationship and performance history.'],[s.label,'Midnight Mannequin / The Feel','Prior catalog and label-era context.'],[s.midnight,'The Midnight official site','Creative-world and owned-fan mechanics.'],[s.strike,'The Strike official site','Music, live and performance routing.'],[s.oakley,'Michael Oakley official site','Album focus and catalog reference.'],
    ].map(([url,title,note])=><li key={url}><External href={url}>{title}</External><span>{note}</span></li>)}</ol><p className="hr-small">Research conducted September 29, 2026. Public counts can change. Archive photographs are supplied by Heartracer’s official website; the live keyboard photograph carries Adam Kliebenstein’s credit. Thumbnails and album art are used here as source references for this proposal. Unverified metrics and private-account gaps are stated rather than estimated.</p></section>
  </div></div>
</main><footer className="hr-footer"><span className="hr-mono">CROWD CONTROL DIGITAL / HEARTRACER</span><Link href="/heartracer">Back to the proposal ↗</Link><a href="mailto:geoff@crowdcontroldigital.com">geoff@crowdcontroldigital.com</a></footer></div>; }
