'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { sources } from './sources';
import './style.css';

const assets = '/images/heartracer/';
const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
const mail = 'mailto:geoff@crowdcontroldigital.com?subject=Heartracer%20%E2%80%94%20confirm%20scope%20and%20first%20invoice';

export function Header({ research = false }: { research?: boolean }) {
  return <header className="hr-header"><Link href="/heartracer" aria-label="Crowd Control Digital, Heartracer proposal"><img src="/brand/CC-LOGO-2024-WHITE.png" alt="Crowd Control Digital" width="114" height="32" /></Link><span className="hr-mono">HEARTRACER / {research ? 'RESEARCH NOTES' : 'PROPOSAL 01'}<br /><span className="hr-muted">SEPTEMBER 29, 2026</span></span><Link className="hr-header-link" href={research ? '/heartracer' : '/heartracer/research'}>{research ? 'The proposal' : 'Research appendix'} <span aria-hidden="true">↗</span></Link></header>;
}

function Label({ n, text }: { n: string; text: string }) { return <p className="hr-label"><span>{n}</span>{text}</p>; }
function Arrow() { return <span className="hr-arrow" aria-hidden="true">↗</span>; }
function Cite({ href, children }: { href: string; children: React.ReactNode }) { return <a className="hr-cite" href={href} target="_blank" rel="noreferrer">{children} ↗</a>; }

const concepts = [
  { name: 'The night drive', title: 'A song worth taking the long way home for.', image: 'dublin.jpg', label: 'STREETS OF DUBLIN / DISCOVERY', hook: 'For the drive you wish would last a little longer.', structure: ['00–02 / Start on the strongest vocal or instrumental moment.', '02–12 / Let the hook play over a human, moving scene.', '12–18 / Name the song. Offer one immediate listening action.'], why: 'Listeners already describe driving-playlist use and replaying “Streets of Dublin.” We turn that use case into a clear invitation.', test: 'Vocal hook vs. instrumental reveal. US audience vs. a separate Ireland test. Same destination and creative in both markets.', action: 'Listen to Streets of Dublin', source: sources.dublin },
  { name: 'Inside the room', title: 'Give the song a person to belong to.', image: 'moonlight.jpg', label: 'ARTIST STORY / CONNECTION', hook: 'Two and a half years. Here’s the part we kept coming back to.', structure: ['00–02 / A candid sentence from Chris or Chip.', '02–08 / A specific writing or recording detail.', '08–22 / Pay it off with the finished song or a stripped performance.'], why: 'The meeting called for emotional attachment to the album. Existing acoustic Shorts and warm replies give us an authentic foundation.', test: 'Chris telling the story vs. Chip showing a guitar part. Direct-to-camera vs. rehearsal performance. Captions remain legible with sound off.', action: 'Hear the finished song', source: sources.youtube },
  { name: 'Fever after dark', title: 'An album world you can step into.', image: 'album.jpg', label: 'NIGHTTIME FEVER / RELEASE', hook: 'Some songs only make sense after dark.', structure: ['00–02 / A face, a musical impact, or a striking album-world detail.', '02–14 / Cut between performance and a single emotional idea.', '14–20 / After October 23: listen now. Before release: hear the available single.'], why: 'The forest artwork, cinematic videos and “Fever Symptom” series already suggest a world. We make it recognizable while keeping the songs and musicians central.', test: 'Atmosphere-led vs. performance-led openings. Use “Killer On The Run” for a timely October chapter, then test the response.', action: 'Step into Nighttime Fever', source: sources.album },
];

export default function Proposal() {
  const [activeConcept, setActiveConcept] = useState(0);
  const [spend, setSpend] = useState(3000);
  const [hours, setHours] = useState(20);
  const [playing, setPlaying] = useState(false);
  const [activeSection, setActiveSection] = useState('vision');
  const root = useRef<HTMLDivElement>(null);
  const concept = concepts[activeConcept];
  const fee = spend * .15;
  const creative = hours * 100;
  const agency = 4000 + fee + creative;
  const total = agency + spend;

  useEffect(() => {
    const el = root.current; if (!el) return;
    const reveal = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('hr-visible'); reveal.unobserve(entry.target); } }), { threshold: .08 });
    el.querySelectorAll('[data-reveal]').forEach(node => reveal.observe(node));
    const chapters = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) setActiveSection(entry.target.id); }); }, { rootMargin: '-25% 0px -55% 0px' });
    el.querySelectorAll('[data-chapter]').forEach(node => chapters.observe(node));
    return () => { reveal.disconnect(); chapters.disconnect(); };
  }, []);

  return <div className="hr" ref={root}>
    <a className="hr-skip" href="#vision">Skip to proposal</a>
    <Header />
    <main>
      <section className="hr-hero">
        <img className="hr-hero-photo" src={assets + 'moonlight.jpg'} alt="Chris Cosby performing in Heartracer’s Dancin’ In The Moonlight video" fetchPriority="high" />
        <div className="hr-hero-shade" />
        <div className="hr-hero-top hr-mono"><span><i className="hr-dot" /> AUDIENCE DEVELOPMENT & RELEASE MARKETING</span><span>RICHMOND, VIRGINIA<br />OCTOBER → DECEMBER 2026</span></div>
        <div className="hr-hero-body"><p className="hr-mono hr-hero-kicker">A PROPOSAL BY CROWD CONTROL DIGITAL</p><h1>HEARTRACER<span className="hr-period">.</span></h1><div className="hr-hero-bottom"><div><p className="hr-serif">Give the record a life<br />beyond release day.</p><p className="hr-hero-copy">A focused three-month partnership to bring <em>Nighttime Fever</em> to the right listeners—and turn their first listen into a lasting relationship.</p></div><div className="hr-hero-meta hr-mono"><span>PROPOSED START<br /><strong>OCTOBER 01</strong></span><span>ALBUM RELEASE<br /><strong>OCTOBER 23</strong></span><a className="hr-button" href="#vision">Explore the plan <Arrow /></a></div></div></div>
        <div className="hr-hero-foot hr-mono"><span>PREPARED BY GEOFF SHAMES / CO-FOUNDER</span><span>01 — THE NEXT CHAPTER <span aria-hidden="true">↓</span></span></div>
      </section>

      <nav className="hr-chapters" aria-label="Proposal chapters">{[['vision','01','Vision'],['strategy','02','Strategy'],['creative','03','Creative'],['roadmap','04','Roadmap'],['scope','05','Scope'],['investment','06','Investment']].map(([id,n,label]) => <a key={id} href={'#'+id} aria-current={activeSection === id ? 'location' : undefined}><span>{n}</span>{label}</a>)}</nav>

      <section id="vision" data-chapter className="hr-section hr-paper">
        <div className="hr-wrap"><Label n="01" text="THE OPPORTUNITY" /><div className="hr-editorial" data-reveal><h2>You made<br />the record.<br /><span className="hr-serif">Let’s build<br />its audience.</span></h2><div className="hr-lead"><p>You have nine songs, five finished videos, and a clear ambition: reach the listeners who will care enough to come back.</p><p>Our job is to give that work a deliberate path into the world. Find the strongest entry points. Build a recognizable story around the band. Make it easy to listen, stay connected, and show up.</p><p>That foundation also makes the bigger ambitions more credible: meaningful sync opportunities and a support slot with a larger, musically aligned act.</p><span className="hr-small">Album details verified publicly. Five videos and career goals reported in the discovery conversation.</span></div></div>
        <div className="hr-findings" data-reveal><article><span className="hr-mono">01 / REACH HAS HAPPENED</span><strong>208.7K</strong><h3>A Dublin teaser found a much wider audience.</h3><p>One public Short reached 208,707 views. The next task is to understand the source of that reach and build a repeatable route from discovery to returning fans.</p><Cite href={sources.short}>YouTube snapshot / Sep 29</Cite></article><article><span className="hr-mono">02 / CONNECTION IS VISIBLE</span><strong>78</strong><h3>Listener comments with a useful signal.</h3><p>After cleaning 176 comments across four platforms, the retained sample contains music praise, replay, playlist and show intent—and a practical checkout concern. These are clues for creative tests, with a small sample to keep in perspective.</p><Link href="/heartracer/research#sentiment" className="hr-cite">See the sentiment method ↗</Link></article><article><span className="hr-mono">03 / AN ASSET TO ACTIVATE</span><strong>OWNED</strong><h3>The list already exists. Put it to work.</h3><p>Move the existing Excel email list into an appropriate platform, confirm usable permissions, and build a welcome path that connects songs, shows and future releases.</p><span className="hr-small">Band-reported / discovery call</span></article></div>
        <div className="hr-thesis" data-reveal><span className="hr-mono">THE CENTRAL IDEA</span><p>Music for the long way home.<br /><span className="hr-serif">A band worth coming back to.</span></p><span className="hr-small">Proposed campaign positioning, informed by the band’s cinematic sound and observed listener language.</span></div></div>
      </section>

      <section id="strategy" data-chapter className="hr-section hr-dark"><div className="hr-wrap"><Label n="02" text="HOW THE AUDIENCE GROWS" /><div className="hr-section-heading" data-reveal><h2>First listen.<br /><span className="hr-serif">Lasting connection.</span></h2><p>Each stage gives someone a reason to take the next step. We measure those steps separately so a large view count never stands in for a fan relationship.</p></div>
        <div className="hr-flywheel" data-reveal>{[
          ['01','DISCOVER','Lead with the part that makes someone stop.','Test song moments, performance and artist-story openings. Start with available music and tightly defined audiences.','Track / qualified visits, engaged video views'],
          ['02','CONNECT','Let people meet Chris, Chip and Wes.','Use songwriting stories, stripped performances and the details behind the record to deepen the introduction.','Track / saves, follows, meaningful responses'],
          ['03','RETURN','Give interested listeners a direct way back.','Invite email sign-ups with a clear benefit, a welcoming first message and location-aware release or show updates.','Track / confirmed sign-ups, clicks, repeat engagement'],
          ['04','BUILD PROOF','Make the audience evidence useful.','Summarize engaged cities, fan responses and live creative in a concise opportunity packet for the band’s booking and sync partners.','Track / usable EPK, verified contacts, partner feedback'],
        ].map(([n,title,head,body,track]) => <article key={n}><span className="hr-flywheel-number">{n}</span><span className="hr-mono">{title}</span><div><h3>{head}</h3><p>{body}</p><span className="hr-small">{track}</span></div><span aria-hidden="true">↘</span></article>)}</div>
        <div className="hr-audience" data-reveal><div><p className="hr-mono">THREE STARTING AUDIENCE HYPOTHESES</p><h3>Meet them<br /><span className="hr-serif">where the music fits.</span></h3><p>These are testable groups, rather than a claimed demographic profile. Actual age, geography and conversion data come from account access at onboarding.</p></div><div>{[
          ['The cinematic listener','Drawn to the feeling of a drive, a place, a memory. Start with Streets of Dublin and immediate listening destinations.','Observed: driving playlists, replay, road-trip imagery.'],
          ['The synth-pop explorer','Finds bands through adjacent artists, musicianship and sound. Test performances, guitar details and contemporary nostalgia.','Observed: one listener discovered Heartracer through Michael Oakley.'],
          ['The future concert regular','Wants a band to follow and a show to attend. Build local connection, collect city preferences and show the live experience.','Observed: England touring request; Richmond performance history.'],
        ].map(([title,body,evidence]) => <article key={title}><h4>{title}</h4><p>{body}</p><span className="hr-small">{evidence}</span></article>)}</div></div>
        <div className="hr-pullquote" data-reveal><span className="hr-mono">A LISTENER PUT IT SIMPLY</span><blockquote>“This is going straight<br />to my driving playlist!”</blockquote><Cite href={sources.dublin}>Public YouTube comment / Streets of Dublin</Cite></div>
      </div></section>

      <section className="hr-film"><img src={assets+'band.jpg'} alt="Heartracer performing at The Broadberry in Richmond" loading="lazy" /><div><p className="hr-mono">THE BIGGER AMBITION</p><p className="hr-serif">Build a fan base<br />you can take on the road.</p><span>Audience development supports the pitch. Booking and sync decisions remain with the relevant buyers and partners.</span></div><p className="hr-photo-credit hr-mono">ARCHIVE LIVE PHOTOGRAPH / HEARTRACER’S OFFICIAL SITE</p></section>

      <section id="creative" data-chapter className="hr-section hr-paper"><div className="hr-wrap"><Label n="03" text="THE CREATIVE DIRECTION" /><div className="hr-section-heading" data-reveal><h2>Let the songs<br /><span className="hr-serif">open the door.</span></h2><p>Use the videos you have. Add the human context only the band can give. Then test the opening, the musical moment and the invitation.</p></div>
        <div className="hr-concept-tabs" role="tablist" aria-label="Creative concepts">{concepts.map((c,i) => <button key={c.name} id={'concept-tab-'+i} role="tab" aria-selected={i===activeConcept} aria-controls="concept-panel" tabIndex={i===activeConcept ? 0 : -1} onClick={()=>setActiveConcept(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(activeConcept+(e.key==='ArrowRight'?1:2))%3;setActiveConcept(next);document.getElementById('concept-tab-'+next)?.focus();}}}><span className="hr-mono">0{i+1}</span>{c.name}<Arrow /></button>)}</div>
        <div className="hr-concept" id="concept-panel" role="tabpanel" aria-labelledby={'concept-tab-'+activeConcept}><div className={'hr-concept-visual '+(activeConcept===2?'hr-album-visual':'')}><img src={assets+concept.image} alt={activeConcept===2?'Official Nighttime Fever album artwork':'Official Heartracer video thumbnail used as a creative direction reference'} loading="lazy" /><div><span className="hr-mono">PROPOSED CREATIVE / COPY STUDY</span><h3 className="hr-serif">{concept.title}</h3><span className="hr-mono">HEARTRACER → {concept.action}</span></div></div><div className="hr-concept-copy"><p className="hr-mono">{concept.label}</p><h3>The opening line</h3><p className="hr-hook">“{concept.hook}”</p><h4>The cut</h4><ol>{concept.structure.map(s=><li key={s}>{s}</li>)}</ol><h4>Why this is worth testing</h4><p>{concept.why}</p><h4>What we compare</h4><p>{concept.test}</p><Cite href={concept.source}>Source material</Cite></div></div>
        <div className="hr-creative-note"><span className="hr-mono">THE MONTHLY RHYTHM</span><p><strong>4 creative briefs → up to 12 planned posts → learn and refine.</strong> These concept directions are included in the retainer. Editing, design and production are separately estimated at $100/hour. Publishing depends on approved assets from the band or commissioned production.</p></div>
        <div className="hr-watch"><div><p className="hr-mono">THE ASSET ALREADY IN HAND</p><h3>Streets of Dublin</h3><p>A cinematic introduction to Heartracer’s world.</p></div><div className="hr-video">{playing ? <iframe title="Heartracer — Streets of Dublin official music video" src="https://www.youtube-nocookie.com/embed/SaFQElkKl0k?autoplay=1" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /> : <button onClick={()=>setPlaying(true)} aria-label="Play Streets of Dublin music video"><img src={assets+'dublin.jpg'} alt="Streets of Dublin music video" loading="lazy" /><span>▶ PLAY THE VIDEO</span></button>}</div></div>
      </div></section>

      <section id="roadmap" data-chapter className="hr-section hr-dark"><div className="hr-wrap"><Label n="04" text="THE FIRST THREE MONTHS" /><div className="hr-section-heading" data-reveal><h2>Start October 1.<br /><span className="hr-serif">Keep building.</span></h2><p>A proposed October–December engagement. Launch readiness depends on agreement, funding, account access and approved assets. The album’s public release date is October 23.</p></div>
        <div className="hr-roadmap" data-reveal>{[
          ['01','OCT 01–07','Get ready. Get the first tests live.','Confirm the October 2 Killer On The Run release plan and video timing. Audit account access, approve the budget, check landing links, agree six starting ad variants and establish the baseline.','Deliver / launch checklist, first creative briefs, baseline report'],
          ['02','OCT 08–23','Build the path into the record.','Test the available singles. Introduce the people and stories behind them. Clean and migrate the usable email list, activate a welcome message and prepare the album-release email.','Deliver / audience tests, working capture, album release plan'],
          ['03','OCT 24–NOV 30','Find what earns another listen.','Keep promotion active after release. Compare creative and markets, refresh the strongest material, and follow confirmed sign-ups and engaged listeners over time. Reserve Ireland as a separate controlled test.','Deliver / winning creative patterns, city signals, monthly decisions'],
          ['04','DEC 01–31','Turn the learning into the next chapter.','Compile a focused live and sync readiness packet, coordinate with existing partners, and review audience quality and spend efficiency before recommending the next engagement.','Deliver / opportunity packet, three-month review, next-quarter plan'],
        ].map(([n,date,title,body,deliver]) => <article key={n}><div className="hr-roadmap-date"><span className="hr-mono">{date}</span><span>{n}</span></div><div><h3>{title}</h3><p>{body}</p><span className="hr-small">{deliver}</span></div></article>)}</div>
        <div className="hr-ready" data-reveal><h3>For an October 1 kickoff</h3><p>Confirm the scope and first invoice by September 30. Share the two released singles, the next video, usable list data and account invitations. Nominate one band approver and agree the initial media and creative caps. October 1 can begin with onboarding if ad approvals or access take longer.</p></div>
      </div></section>

      <section id="scope" data-chapter className="hr-section hr-paper"><div className="hr-wrap"><Label n="05" text="THE PARTNERSHIP" /><div className="hr-section-heading" data-reveal><h2>A clear scope.<br /><span className="hr-serif">A working team.</span></h2><p>The $4,000 monthly retainer funds an ongoing release and audience-development partnership. Paid-media operation and creative production are priced separately, transparently.</p></div>
        <div className="hr-scope-grid" data-reveal>{[
          ['01','Strategy & direction','A rolling release plan, audience hypotheses, priorities and a weekly working call. One named CCD lead and one band approval contact.','1 weekly call / 1 monthly strategy update'],
          ['02','Organic content coordination','Up to 12 posts per month planned, captioned and scheduled across two agreed organic channels using approved supplied assets.','4 creative briefs / up to 12 scheduled posts'],
          ['03','Audience & email','Initial clean-up and standard import of the existing usable email list, one welcome message, a basic capture path and two email campaigns per month.','1 list migration / 2 campaigns per month'],
          ['04','Paid-media strategy','Media plan, creative test framework, approved budget caps and reporting interpretation. Trafficking and optimization on up to two platforms are covered by the 15% media fee.','Start with Meta / add YouTube when funded'],
          ['05','Performance & listening','A baseline, weekly performance checks, one monthly report and a refreshed comment/theme review. Daily data refreshes where existing integrations support them.','1 monthly report / clear next actions'],
          ['06','Live & sync readiness','One concise opportunity packet during the engagement: band story, selected music, verified credits, live proof and audience/city evidence. Coordination with the band’s existing partners.','1 opportunity packet / 1 partner handoff'],
        ].map(([n,title,body,qty])=><article key={n}><span className="hr-mono">{n}</span><h3>{title}</h3><p>{body}</p><span className="hr-small">{qty}</span></article>)}</div>
        <div className="hr-boundaries" data-reveal><div><h3>The band brings</h3><p>Account invitations, rights-cleared music and footage, usable fan permissions, timely approvals and a regular filming contribution. We give the prompts and shot lists so the filming feels manageable.</p></div><div><h3>Separately scoped</h3><p>Creative editing, design and production at $100/hour; filming crews, travel, licensing and creator payments; software and SMS charges; web rebuilds, bespoke dashboard development and expanded daily community management.</p></div><div><h3>Opportunity support</h3><p>Booking negotiation, direct sync representation, traditional PR and editorial playlist pitching are outside this scope. We support readiness and partner coordination. Placements and support slots are not promised deliverables.</p></div></div>
        <div className="hr-measure" data-reveal><p className="hr-mono">WHAT SUCCESS LOOKS LIKE</p><h3>Know who is responding.<br /><span className="hr-serif">Know what to do next.</span></h3><div><article><h4>By day 7</h4><p>A verified baseline, approved budget and launch checklist. Confirm what can be tracked before scaling spend.</p></article><article><h4>By day 30</h4><p>Six initial creative variants evaluated, a usable fan welcome path, and clear decisions about creative and market tests.</p></article><article><h4>By month 3</h4><p>A repeatable content rhythm, a consent-based fan database with engagement evidence, and a live/sync readiness packet.</p></article></div><p className="hr-small">These are operating milestones. Audience growth and acquisition-cost targets are set after the initial baseline; no stream, follower or revenue totals are guaranteed.</p></div>
      </div></section>

      <section id="investment" data-chapter className="hr-section hr-dark"><div className="hr-wrap"><Label n="06" text="THE INVESTMENT" /><div className="hr-section-heading" data-reveal><h2>Build deliberately.<br /><span className="hr-serif">Spend transparently.</span></h2><p>No media budget has been agreed. Use the model below to see the complete monthly picture, then choose the starting level together.</p></div>
        <div className="hr-pricing" data-reveal><article><span className="hr-mono">THE PARTNERSHIP</span><strong>$4,000<span>/mo</span></strong><h3>Monthly retainer</h3><p>The strategy, coordination, email and reporting scope above. Proposed three-month initial term, billed monthly in advance.</p></article><article><span className="hr-mono">PAID MEDIA</span><strong>15<span>%</span></strong><h3>Of managed ad spend</h3><p>Campaign setup, trafficking and ongoing optimization on the agreed paid platforms. Applied to actual net platform media spend.</p></article><article><span className="hr-mono">CREATIVE</span><strong>$100<span>/hr</span></strong><h3>Approved production</h3><p>Editing, design and creative production. Each assignment gets an estimate and approval; time is tracked and billed for actual hours.</p></article></div>
        <div className="hr-calculator"><div><p className="hr-mono">EXPLORE A MONTHLY SCENARIO</p><h3>Make the budget<br /><span className="hr-serif">make sense.</span></h3><p>These are illustrations, not commitments or forecasts. Adjust the two inputs to see fees and media separately.</p><label htmlFor="media-spend">Monthly platform ad spend <output>{money(spend)}</output></label><input id="media-spend" type="range" min="0" max="15000" step="250" value={spend} onChange={e=>setSpend(Number(e.target.value))} /><div className="hr-range-labels"><span>$0</span><span>$15,000</span></div><label htmlFor="creative-hours">Approved creative hours <output>{hours} hrs</output></label><input id="creative-hours" type="range" min="0" max="50" step="1" value={hours} onChange={e=>setHours(Number(e.target.value))} /><div className="hr-range-labels"><span>0 hours</span><span>50 hours</span></div></div><div className="hr-budget-output" aria-live="polite" aria-atomic="true"><div className="hr-budget-row"><span>Monthly retainer</span><strong>$4,000</strong></div><div className="hr-budget-row"><span>Media management / 15%</span><strong>{money(fee)}</strong></div><div className="hr-budget-row"><span>Creative / {hours} hrs × $100</span><strong>{money(creative)}</strong></div><div className="hr-budget-row hr-budget-sub"><span>Agency + creative fees</span><strong>{money(agency)}</strong></div><div className="hr-budget-row"><span>Ad spend / paid to platforms</span><strong>{money(spend)}</strong></div><div className="hr-budget-total"><span className="hr-mono">ILLUSTRATIVE MONTHLY TOTAL</span><strong>{money(total)}</strong></div><div className="hr-budget-row"><span>Same scenario for 3 months</span><strong>{money(total*3)}</strong></div><p className="hr-small">Excludes applicable taxes, software and approved third-party expenses. No spend or creative hours are authorized by changing these inputs.</p></div></div>
        <div className="hr-terms"><details><summary>How billing works <span>+</span></summary><p>The proposed initial term is October 1–December 31, 2026, subject to the signed agreement and readiness. Retainer invoices of $4,000 are due at kickoff and at the start of months two and three: $12,000 in fixed retainer fees. Media spend is paid directly to platforms. The 15% fee is reconciled monthly on net media spend, excluding platform taxes, credits and refunds. Creative is billed monthly on actual approved hours. No setup fee is proposed.</p></details><details><summary>Budget control and changes <span>+</span></summary><p>Agree media and creative caps in writing before execution. A creative estimate includes the assignment, hours and revision allowance. Work beyond the approved estimate needs further approval. The retainer includes strategy and briefs; separately commissioned production is not billed as retainer work. Creator fees and non-media vendor expenses are outside the 15% fee base unless separately agreed. Any continuation beyond December requires agreement; an annual commitment is not required.</p></details><details><summary>Start dates, approvals and ownership <span>+</span></summary><p>October 1 is the proposed start, with access, first-month funding and approved assets required for live campaign launch. The band retains ownership of its accounts, media relationships and fan database. Usage and delivery rights for new creative are documented in the agreement, subject to third-party licenses. A two-business-day approval rhythm is proposed; late approvals may move publishing dates. SMS activation depends on appropriate consent and platform availability.</p></details></div>
      </div></section>

      <section className="hr-closing hr-paper"><div className="hr-wrap"><div><p className="hr-mono">THE NEXT CHAPTER STARTS HERE</p><h2>Let’s give<br /><em className="hr-serif">Nighttime Fever</em><br />a longer life.</h2><p>Confirm the scope. Choose the first media and creative caps. Complete the agreement and first-month invoice. Then bring the band and CCD together for onboarding.</p><a href={mail} className="hr-button">Confirm scope & request first invoice <Arrow /></a><p className="hr-small">First-month retainer: $4,000. Onboarding questionnaire follows approval.</p></div><figure><img src={assets+'album.jpg'} alt="Official Nighttime Fever artwork, a forest with Heartracer’s yellow and red waveform" loading="lazy" /><figcaption className="hr-mono">NIGHTTIME FEVER / 9 TRACKS / 10.23.2026</figcaption></figure></div></section>

      <section className="hr-about"><div className="hr-wrap"><span className="hr-mono">WHY CROWD CONTROL DIGITAL</span><div><h3>Music, creative<br /><span className="hr-serif">and distribution.</span></h3><p>CCD brings release strategy, paid-media execution and creative direction into one working relationship. For Heartracer, that means the people shaping the campaign also see how the creative performs—and can give the band a clear next step every week.</p><p className="hr-small">Geoff’s discovery conversation described 15 years of music and brand marketing experience. Relevant case studies can be shared directly; they are not used here to predict Heartracer’s results.</p></div></div></section>
    </main><footer className="hr-footer"><span className="hr-mono">HEARTRACER / CROWD CONTROL DIGITAL / 2026</span><Link href="/heartracer/research">Read the research appendix <Arrow /></Link><a href="mailto:geoff@crowdcontroldigital.com">geoff@crowdcontroldigital.com</a><span className="hr-small">Proposal for discussion. Final scope and terms are governed by the signed agreement.</span></footer>
  </div>;
}
