export const sources = {
  official: 'https://www.playheartracer.com/',
  bio: 'https://www.playheartracer.com/bio',
  album: 'https://heartracer.bandcamp.com/album/nighttime-fever',
  linktree: 'https://linktr.ee/playheartracer',
  youtube: 'https://www.youtube.com/@Heartracer',
  dublin: 'https://www.youtube.com/watch?v=SaFQElkKl0k',
  moonlight: 'https://www.youtube.com/watch?v=eBBpfPmW6SY',
  dateNight: 'https://www.youtube.com/watch?v=47uBIj16yGk',
  room: 'https://www.youtube.com/watch?v=eG1nSCztqtY',
  ghost: 'https://www.youtube.com/watch?v=l4d9wNC0yQQ',
  short: 'https://www.youtube.com/shorts/zAHeDESn3Nc',
  shortDate: 'https://www.youtube.com/shorts/F1AMpBmulJM',
  shortConflict: 'https://www.youtube.com/shorts/sKzN0VlzKUM',
  midnight: 'https://themidnightofficial.com/',
  strike: 'https://www.wearethestrike.com/',
  oakley: 'https://www.michael-oakley.com/',
  oakleyCatalog: 'https://michaeloakleyofficial.bandcamp.com/',
  label: 'https://midnightmannequin.bandcamp.com/album/the-feel',
  richmond: 'https://richmondmagazine.com/arts-entertainment/music/heartracer/',
  instagram: 'https://www.instagram.com/playheartracer/',
  facebook: 'https://www.facebook.com/playheartracer',
  twitter: 'https://x.com/playheartracer',
};
